spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=Bhuppi@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=23nd28fnns028vnms2f73bc29f249fndk2c8n3ncnwq38472b
jwt.expiration=86400000
spring.data.redis.host=localhost
spring.data.redis.port=6379